import { ComplianceControl, ComplianceFramework, ControlSeverity } from '../entities/compliance.entity';

/**
 * NIST 800-53 Rev 5 Controls
 * Rev 5 introduced significant changes including new control families and structure.
 * This is a comprehensive but not exhaustive list.
 */
export const NIST_800_53_REV_5_CONTROLS: ComplianceControl[] = [
  // Access Control (AC) Family - Similar to Rev 4 but with enhancements
  {
    id: 'nist-800-53-rev5-ac-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AC-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate access control policy and procedures.',
    family: 'Access Control',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish and maintain access control policies that define roles, responsibilities, and procedures.',
    assessmentGuidance: 'Review policy documentation and verify procedures are followed.',
  },
  {
    id: 'nist-800-53-rev5-ac-2',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AC-2',
    title: 'Account Management',
    description: 'Manage information system accounts, including establishing, activating, modifying, disabling, and removing accounts.',
    family: 'Access Control',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement automated account management processes with approval workflows.',
    assessmentGuidance: 'Review account creation/modification logs and verify approval processes.',
  },
  {
    id: 'nist-800-53-rev5-ac-3',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AC-3',
    title: 'Access Enforcement',
    description: 'Enforce approved authorizations for logical access to information and system resources.',
    family: 'Access Control',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement role-based access control (RBAC) or attribute-based access control (ABAC).',
    assessmentGuidance: 'Test access controls by attempting unauthorized access.',
  },
  {
    id: 'nist-800-53-rev5-ac-4',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AC-4',
    title: 'Information Flow Enforcement',
    description: 'Enforce approved authorizations for controlling the flow of information within the system and between interconnected systems.',
    family: 'Access Control',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement data loss prevention (DLP) and network segmentation.',
    assessmentGuidance: 'Review network flow logs and data access patterns.',
  },
  {
    id: 'nist-800-53-rev5-ac-5',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AC-5',
    title: 'Separation of Duties',
    description: 'Separate duties of individuals as needed to prevent malevolent activity without collusion.',
    family: 'Access Control',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Ensure no single individual has conflicting responsibilities.',
    assessmentGuidance: 'Review role assignments and verify separation of duties.',
  },
  {
    id: 'nist-800-53-rev5-ac-6',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AC-6',
    title: 'Least Privilege',
    description: 'Employ the principle of least privilege, allowing only authorized accesses necessary to accomplish assigned tasks.',
    family: 'Access Control',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Grant minimum necessary permissions and review regularly.',
    assessmentGuidance: 'Audit user permissions and verify they match job requirements.',
  },
  
  // Supply Chain Risk Management (SR) Family - NEW in Rev 5
  {
    id: 'nist-800-53-rev5-sr-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate supply chain risk management policy and procedures.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish supply chain risk management policies and procedures.',
    assessmentGuidance: 'Review policy documentation and verify procedures are followed.',
  },
  {
    id: 'nist-800-53-rev5-sr-2',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-2',
    title: 'Supply Chain Risk Management Plan',
    description: 'Develop and document a supply chain risk management plan.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Document supply chain risks and mitigation strategies.',
    assessmentGuidance: 'Review supply chain risk management plan.',
  },
  {
    id: 'nist-800-53-rev5-sr-3',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-3',
    title: 'Supply Chain Controls and Processes',
    description: 'Employ security controls and processes to manage supply chain risks.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement vendor risk assessments and security requirements.',
    assessmentGuidance: 'Review vendor security assessments and contracts.',
  },
  {
    id: 'nist-800-53-rev5-sr-4',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-4',
    title: 'Provenance',
    description: 'Document and maintain the provenance of critical software, firmware, and hardware components.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Maintain software bill of materials (SBOM) and component tracking.',
    assessmentGuidance: 'Review component provenance documentation.',
  },
  {
    id: 'nist-800-53-rev5-sr-5',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-5',
    title: 'Acquisition Strategies, Tools, and Methods',
    description: 'Employ acquisition strategies, contract tools, and procurement methods to protect against supply chain risks.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Include security requirements in procurement contracts.',
    assessmentGuidance: 'Review procurement contracts and verify security requirements.',
  },
  {
    id: 'nist-800-53-rev5-sr-6',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-6',
    title: 'Supplier Assessments and Reviews',
    description: 'Assess and review the supply chain-related security posture of suppliers.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct regular supplier security assessments.',
    assessmentGuidance: 'Review supplier assessment reports.',
  },
  {
    id: 'nist-800-53-rev5-sr-7',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-7',
    title: 'Supply Chain Operations Security',
    description: 'Employ security controls and processes to protect supply chain operations.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement secure supply chain processes and monitoring.',
    assessmentGuidance: 'Review supply chain security controls.',
  },
  {
    id: 'nist-800-53-rev5-sr-8',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-8',
    title: 'Notification Agreements',
    description: 'Establish agreements and procedures with entities involved in the supply chain.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish notification procedures for security incidents.',
    assessmentGuidance: 'Review supplier notification agreements.',
  },
  {
    id: 'nist-800-53-rev5-sr-9',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-9',
    title: 'Tamper Resistance and Detection',
    description: 'Implement tamper resistance and detection mechanisms for critical system components.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Use tamper-evident packaging and hardware security modules.',
    assessmentGuidance: 'Verify tamper resistance mechanisms are implemented.',
  },
  {
    id: 'nist-800-53-rev5-sr-10',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-10',
    title: 'Inspection of Systems or Components',
    description: 'Inspect systems or system components to detect tampering.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct regular inspections of critical components.',
    assessmentGuidance: 'Review inspection records and verify inspections are conducted.',
  },
  {
    id: 'nist-800-53-rev5-sr-11',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-11',
    title: 'Component Authenticity',
    description: 'Employ anti-counterfeit technologies and methods to detect counterfeit components.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Verify component authenticity using cryptographic signatures or certificates.',
    assessmentGuidance: 'Review component authenticity verification processes.',
  },
  {
    id: 'nist-800-53-rev5-sr-12',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SR-12',
    title: 'Component Disposal',
    description: 'Dispose of information system components using approved methods.',
    family: 'Supply Chain Risk Management',
    priority: ControlSeverity.LOW,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish secure disposal procedures for components.',
    assessmentGuidance: 'Review disposal procedures and verify they are followed.',
  },
  
  // System and Information Integrity (SI) Family - Enhanced in Rev 5
  {
    id: 'nist-800-53-rev5-si-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SI-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate system and information integrity policy and procedures.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish system and information integrity policies.',
    assessmentGuidance: 'Review policy documentation.',
  },
  {
    id: 'nist-800-53-rev5-si-2',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SI-2',
    title: 'Flaw Remediation',
    description: 'Identify, report, and correct information system flaws.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish vulnerability management process with patching timelines.',
    assessmentGuidance: 'Review patch management logs and verify critical patches are applied within SLA.',
  },
  {
    id: 'nist-800-53-rev5-si-3',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SI-3',
    title: 'Malicious Code Protection',
    description: 'Employ malicious code protection mechanisms at information system entry and exit points.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Deploy antivirus/anti-malware solutions and keep signatures updated.',
    assessmentGuidance: 'Verify antivirus is installed, updated, and scanning.',
  },
  {
    id: 'nist-800-53-rev5-si-4',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SI-4',
    title: 'System Monitoring',
    description: 'Monitor the system to detect attacks and indicators of potential attacks.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement security information and event management (SIEM) system.',
    assessmentGuidance: 'Review monitoring logs and verify alerts are configured.',
  },
  {
    id: 'nist-800-53-rev5-si-7',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SI-7',
    title: 'Software, Firmware, and Information Integrity',
    description: 'Employ integrity verification tools to detect unauthorized changes to software, firmware, and information.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement file integrity monitoring (FIM) and code signing.',
    assessmentGuidance: 'Review integrity check logs and verify unauthorized changes are detected.',
  },
  {
    id: 'nist-800-53-rev5-si-12',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SI-12',
    title: 'Information Management and Retention',
    description: 'Manage and retain information within the system and information output from the system.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish data retention and disposal policies.',
    assessmentGuidance: 'Review data retention policies and verify they are followed.',
  },
  
  // Audit and Accountability (AU) Family - Similar to Rev 4
  {
    id: 'nist-800-53-rev5-au-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AU-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate audit and accountability policy and procedures.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish audit and accountability policies.',
    assessmentGuidance: 'Review policy documentation.',
  },
  {
    id: 'nist-800-53-rev5-au-2',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AU-2',
    title: 'Event Logging',
    description: 'Ensure that the system is capable of logging events.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Enable audit logging for authentication, authorization, and data access events.',
    assessmentGuidance: 'Verify audit logs capture required events.',
  },
  {
    id: 'nist-800-53-rev5-au-3',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AU-3',
    title: 'Content of Audit Records',
    description: 'Ensure that audit records contain information that establishes what type of event occurred, when, where, and the outcome.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Ensure audit logs include timestamp, user, action, resource, and result.',
    assessmentGuidance: 'Review sample audit logs and verify required fields are present.',
  },
  {
    id: 'nist-800-53-rev5-au-4',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AU-4',
    title: 'Audit Log Storage Capacity',
    description: 'Allocate audit log storage capacity and configure auditing to reduce the likelihood of such capacity being exceeded.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Configure log rotation and retention policies.',
    assessmentGuidance: 'Verify log storage capacity and rotation policies.',
  },
  {
    id: 'nist-800-53-rev5-au-5',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AU-5',
    title: 'Response to Audit Processing Failures',
    description: 'Alert designated organizational officials in the event of an audit processing failure.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Configure alerts for audit log failures and storage capacity issues.',
    assessmentGuidance: 'Test audit failure scenarios and verify alerts are sent.',
  },
  {
    id: 'nist-800-53-rev5-au-6',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AU-6',
    title: 'Audit Record Review, Analysis, and Reporting',
    description: 'Review and analyze audit records for indications of inappropriate or unusual activity.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish regular audit review schedule and automated analysis.',
    assessmentGuidance: 'Review audit analysis reports and verify reviews are conducted regularly.',
  },
  {
    id: 'nist-800-53-rev5-au-7',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AU-7',
    title: 'Audit Record Reduction and Report Generation',
    description: 'Provide an audit record reduction and report generation capability.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement SIEM or log analysis tools for report generation.',
    assessmentGuidance: 'Verify audit reports can be generated and reviewed.',
  },
  {
    id: 'nist-800-53-rev5-au-8',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AU-8',
    title: 'Time Stamps',
    description: 'Use internal system clocks to generate time stamps for audit records.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Synchronize system clocks using NTP.',
    assessmentGuidance: 'Verify time synchronization is configured and working.',
  },
  {
    id: 'nist-800-53-rev5-au-9',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'AU-9',
    title: 'Protection of Audit Information',
    description: 'Protect audit information and audit tools from unauthorized access, modification, and deletion.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Restrict access to audit logs and implement log integrity protection.',
    assessmentGuidance: 'Verify audit log access controls and integrity mechanisms.',
  },
  
  // Identification and Authentication (IA) Family
  {
    id: 'nist-800-53-rev5-ia-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate identification and authentication policy and procedures.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish identification and authentication policies.',
    assessmentGuidance: 'Review policy documentation.',
  },
  {
    id: 'nist-800-53-rev5-ia-2',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-2',
    title: 'Identification and Authentication (Organizational Users)',
    description: 'Uniquely identify and authenticate organizational users.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement unique user IDs and strong authentication mechanisms.',
    assessmentGuidance: 'Verify user identification and authentication processes.',
  },
  {
    id: 'nist-800-53-rev5-ia-3',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-3',
    title: 'Device Identification and Authentication',
    description: 'Uniquely identify and authenticate devices before establishing a connection.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement device certificates or MAC address filtering.',
    assessmentGuidance: 'Verify device authentication is enforced.',
  },
  {
    id: 'nist-800-53-rev5-ia-4',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-4',
    title: 'Identifier Management',
    description: 'Manage information system identifiers by receiving authorization from a designated organizational official.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish identifier assignment and management procedures.',
    assessmentGuidance: 'Review identifier management processes and verify authorization.',
  },
  {
    id: 'nist-800-53-rev5-ia-5',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-5',
    title: 'Authenticator Management',
    description: 'Manage information system authenticators by establishing initial authenticator content, receiving authorization, and distributing authenticators.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement password policies, MFA, and secure authenticator distribution.',
    assessmentGuidance: 'Review authenticator management processes and verify compliance with policies.',
  },
  {
    id: 'nist-800-53-rev5-ia-6',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-6',
    title: 'Authenticator Feedback',
    description: 'Obscure feedback of authentication information during the authentication process.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.LOW,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Mask passwords and sensitive input during authentication.',
    assessmentGuidance: 'Verify password masking and secure input handling.',
  },
  {
    id: 'nist-800-53-rev5-ia-7',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-7',
    title: 'Cryptographic Module Authentication',
    description: 'Implement mechanisms for authentication to a cryptographic module.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Use FIPS 140-2 validated cryptographic modules.',
    assessmentGuidance: 'Verify cryptographic modules are FIPS 140-2 validated.',
  },
  {
    id: 'nist-800-53-rev5-ia-8',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-8',
    title: 'Identification and Authentication (Non-Organizational Users)',
    description: 'Uniquely identify and authenticate non-organizational users.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement authentication for external users and partners.',
    assessmentGuidance: 'Verify non-organizational user authentication processes.',
  },
  {
    id: 'nist-800-53-rev5-ia-11',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-11',
    title: 'Re-authentication',
    description: 'Require users and devices to re-authenticate when organization-defined circumstances or events occur.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Configure re-authentication triggers (e.g., after period of inactivity, privilege escalation).',
    assessmentGuidance: 'Verify re-authentication is enforced when required.',
  },
  {
    id: 'nist-800-53-rev5-ia-12',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IA-12',
    title: 'Identity Proofing',
    description: 'Identity proof users before establishing accounts.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Verify user identity before account creation.',
    assessmentGuidance: 'Review identity proofing processes and verify they are followed.',
  },
  
  // Configuration Management (CM) Family
  {
    id: 'nist-800-53-rev5-cm-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CM-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate configuration management policy and procedures.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish configuration management policies.',
    assessmentGuidance: 'Review policy documentation.',
  },
  {
    id: 'nist-800-53-rev5-cm-2',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CM-2',
    title: 'Baseline Configuration',
    description: 'Develop, document, and maintain baseline configurations for information systems.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Document and version control system configurations.',
    assessmentGuidance: 'Review baseline configuration documentation and verify it is maintained.',
  },
  {
    id: 'nist-800-53-rev5-cm-3',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CM-3',
    title: 'Configuration Change Control',
    description: 'Determine the types of changes to the information system that are configuration-controlled.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish change management process with approval workflows.',
    assessmentGuidance: 'Review change logs and verify approval processes are followed.',
  },
  {
    id: 'nist-800-53-rev5-cm-4',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CM-4',
    title: 'Security Impact Analysis',
    description: 'Analyze changes to the information system to determine potential security impacts.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Perform security impact analysis for all configuration changes.',
    assessmentGuidance: 'Review security impact analyses and verify they are conducted.',
  },
  {
    id: 'nist-800-53-rev5-cm-5',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CM-5',
    title: 'Access Restrictions for Change',
    description: 'Define, document, approve, and enforce physical and logical access restrictions associated with changes.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Restrict configuration change access to authorized personnel.',
    assessmentGuidance: 'Review access controls and verify only authorized users can make changes.',
  },
  {
    id: 'nist-800-53-rev5-cm-6',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CM-6',
    title: 'Configuration Settings',
    description: 'Establish and document configuration settings for information technology products.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Use security configuration guides (e.g., DISA STIGs, CIS Benchmarks).',
    assessmentGuidance: 'Verify systems are configured according to security baselines.',
  },
  {
    id: 'nist-800-53-rev5-cm-7',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CM-7',
    title: 'Least Functionality',
    description: 'Configure the information system to provide only essential capabilities.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Disable unnecessary services and ports.',
    assessmentGuidance: 'Review system configurations and verify unnecessary services are disabled.',
  },
  {
    id: 'nist-800-53-rev5-cm-8',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CM-8',
    title: 'System Component Inventory',
    description: 'Develop and document an inventory of information system components.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Maintain asset inventory with automated discovery where possible.',
    assessmentGuidance: 'Review inventory and verify it is accurate and up-to-date.',
  },
  
  // Contingency Planning (CP) Family
  {
    id: 'nist-800-53-rev5-cp-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CP-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate contingency planning policy and procedures.',
    family: 'Contingency Planning',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish contingency planning policies.',
    assessmentGuidance: 'Review policy documentation.',
  },
  {
    id: 'nist-800-53-rev5-cp-2',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CP-2',
    title: 'Contingency Plan',
    description: 'Develop and document a contingency plan for the information system.',
    family: 'Contingency Planning',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Document recovery procedures and test regularly.',
    assessmentGuidance: 'Review contingency plan and verify it is tested.',
  },
  {
    id: 'nist-800-53-rev5-cp-3',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CP-3',
    title: 'Contingency Training',
    description: 'Provide contingency training to information system users.',
    family: 'Contingency Planning',
    priority: ControlSeverity.LOW,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct regular training on contingency procedures.',
    assessmentGuidance: 'Review training records and verify training is conducted.',
  },
  {
    id: 'nist-800-53-rev5-cp-4',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'CP-4',
    title: 'Contingency Plan Testing',
    description: 'Test the contingency plan for the information system.',
    family: 'Contingency Planning',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct tabletop exercises and full recovery tests.',
    assessmentGuidance: 'Review test results and verify tests are conducted regularly.',
  },
  
  // Incident Response (IR) Family
  {
    id: 'nist-800-53-rev5-ir-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IR-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate incident response policy and procedures.',
    family: 'Incident Response',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish incident response policies.',
    assessmentGuidance: 'Review policy documentation.',
  },
  {
    id: 'nist-800-53-rev5-ir-4',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IR-4',
    title: 'Incident Handling',
    description: 'Implement an incident handling capability for security incidents.',
    family: 'Incident Response',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish incident response team and procedures.',
    assessmentGuidance: 'Review incident logs and verify incidents are handled according to procedures.',
  },
  {
    id: 'nist-800-53-rev5-ir-5',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IR-5',
    title: 'Incident Monitoring',
    description: 'Track and document information system security incidents.',
    family: 'Incident Response',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Maintain incident tracking system and monitor for security events.',
    assessmentGuidance: 'Review incident tracking logs and verify monitoring is active.',
  },
  {
    id: 'nist-800-53-rev5-ir-6',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'IR-6',
    title: 'Incident Reporting',
    description: 'Require personnel to report suspected security incidents.',
    family: 'Incident Response',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish reporting procedures and communication channels.',
    assessmentGuidance: 'Verify reporting procedures are documented and communicated.',
  },
  
  // Risk Assessment (RA) Family
  {
    id: 'nist-800-53-rev5-ra-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'RA-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate risk assessment policy and procedures.',
    family: 'Risk Assessment',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish risk assessment policies.',
    assessmentGuidance: 'Review policy documentation.',
  },
  {
    id: 'nist-800-53-rev5-ra-2',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'RA-2',
    title: 'Security Categorization',
    description: 'Categorize the information system and the information it processes, stores, and transmits.',
    family: 'Risk Assessment',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Categorize systems according to FIPS 199.',
    assessmentGuidance: 'Review security categorization documentation.',
  },
  {
    id: 'nist-800-53-rev5-ra-3',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'RA-3',
    title: 'Risk Assessment',
    description: 'Conduct risk assessments to identify threats, vulnerabilities, and risks.',
    family: 'Risk Assessment',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct regular risk assessments and document findings.',
    assessmentGuidance: 'Review risk assessment reports and verify they are current.',
  },
  {
    id: 'nist-800-53-rev5-ra-5',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'RA-5',
    title: 'Vulnerability Monitoring and Scanning',
    description: 'Monitor and scan for vulnerabilities in the information system and applications.',
    family: 'Risk Assessment',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct regular vulnerability scans and remediate findings.',
    assessmentGuidance: 'Review scan results and verify vulnerabilities are tracked and remediated.',
  },
  
  // System and Communications Protection (SC) Family
  {
    id: 'nist-800-53-rev5-sc-1',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SC-1',
    title: 'Policy and Procedures',
    description: 'Develop, document, and disseminate system and communications protection policy and procedures.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish system and communications protection policies.',
    assessmentGuidance: 'Review policy documentation.',
  },
  {
    id: 'nist-800-53-rev5-sc-5',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SC-5',
    title: 'Denial of Service Protection',
    description: 'Protect against or limit the effects of denial-of-service attacks.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement rate limiting, DDoS protection, and resource quotas.',
    assessmentGuidance: 'Review DoS protection configurations and test resilience.',
  },
  {
    id: 'nist-800-53-rev5-sc-7',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SC-7',
    title: 'Boundary Protection',
    description: 'Monitor and control communications at the external boundary and key internal boundaries.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement firewalls, network segmentation, and traffic filtering.',
    assessmentGuidance: 'Review firewall rules and network segmentation.',
  },
  {
    id: 'nist-800-53-rev5-sc-8',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SC-8',
    title: 'Transmission Confidentiality and Integrity',
    description: 'Protect the confidentiality and integrity of transmitted information.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Use TLS/SSL for data in transit and verify certificates.',
    assessmentGuidance: 'Review TLS configurations and verify encryption is enforced.',
  },
  {
    id: 'nist-800-53-rev5-sc-12',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SC-12',
    title: 'Cryptographic Key Establishment and Management',
    description: 'Establish and manage cryptographic keys for required cryptography.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement key management system with key rotation policies.',
    assessmentGuidance: 'Review key management procedures and verify keys are rotated.',
  },
  {
    id: 'nist-800-53-rev5-sc-13',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SC-13',
    title: 'Cryptographic Protection',
    description: 'Implement cryptographic mechanisms.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Use approved cryptographic algorithms and key lengths.',
    assessmentGuidance: 'Verify cryptographic implementations meet requirements.',
  },
  {
    id: 'nist-800-53-rev5-sc-28',
    framework: ComplianceFramework.NIST_800_53_REV_5,
    controlId: 'SC-28',
    title: 'Protection of Information at Rest',
    description: 'Protect the confidentiality and integrity of information at rest.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Encrypt sensitive data at rest using approved algorithms.',
    assessmentGuidance: 'Verify encryption is enabled for data at rest.',
  },
];

