import { ComplianceControl, ComplianceFramework, ControlSeverity } from '../entities/compliance.entity';

/**
 * NIST 800-53 Rev 4 Controls
 * This is a comprehensive but not exhaustive list of controls.
 * In production, this would be loaded from an authoritative source or database.
 */
export const NIST_800_53_REV_4_CONTROLS: ComplianceControl[] = [
  // Access Control (AC) Family
  {
    id: 'nist-800-53-rev4-ac-1',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-1',
    title: 'Access Control Policy and Procedures',
    description: 'The organization develops, documents, and disseminates access control policy and procedures.',
    family: 'Access Control',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish and maintain access control policies that define roles, responsibilities, and procedures.',
    assessmentGuidance: 'Review policy documentation and verify procedures are followed.',
  },
  {
    id: 'nist-800-53-rev4-ac-2',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-2',
    title: 'Account Management',
    description: 'The organization manages information system accounts, including establishing, activating, modifying, disabling, and removing accounts.',
    family: 'Access Control',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement automated account management processes with approval workflows.',
    assessmentGuidance: 'Review account creation/modification logs and verify approval processes.',
  },
  {
    id: 'nist-800-53-rev4-ac-3',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-3',
    title: 'Access Enforcement',
    description: 'The information system enforces approved authorizations for logical access to information and system resources.',
    family: 'Access Control',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement role-based access control (RBAC) or attribute-based access control (ABAC).',
    assessmentGuidance: 'Test access controls by attempting unauthorized access.',
  },
  {
    id: 'nist-800-53-rev4-ac-4',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-4',
    title: 'Information Flow Enforcement',
    description: 'The information system enforces approved authorizations for controlling the flow of information within the system and between interconnected systems.',
    family: 'Access Control',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement data loss prevention (DLP) and network segmentation.',
    assessmentGuidance: 'Review network flow logs and data access patterns.',
  },
  {
    id: 'nist-800-53-rev4-ac-5',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-5',
    title: 'Separation of Duties',
    description: 'The organization separates duties of individuals as needed to prevent malevolent activity without collusion.',
    family: 'Access Control',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Ensure no single individual has conflicting responsibilities.',
    assessmentGuidance: 'Review role assignments and verify separation of duties.',
  },
  {
    id: 'nist-800-53-rev4-ac-6',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-6',
    title: 'Least Privilege',
    description: 'The organization employs the principle of least privilege, allowing only authorized accesses for users (and processes acting on behalf of users) which are necessary to accomplish assigned tasks.',
    family: 'Access Control',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Grant minimum necessary permissions and review regularly.',
    assessmentGuidance: 'Audit user permissions and verify they match job requirements.',
  },
  {
    id: 'nist-800-53-rev4-ac-7',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-7',
    title: 'Unsuccessful Logon Attempts',
    description: 'The information system enforces a limit of consecutive invalid logon attempts by a user during a time period.',
    family: 'Access Control',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement account lockout after failed attempts (e.g., 5 attempts in 15 minutes).',
    assessmentGuidance: 'Test account lockout functionality and review lockout logs.',
  },
  {
    id: 'nist-800-53-rev4-ac-8',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-8',
    title: 'System Use Notification',
    description: 'The information system displays an approved system use notification message before granting access.',
    family: 'Access Control',
    priority: ControlSeverity.LOW,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Display banner warning about authorized use only.',
    assessmentGuidance: 'Verify banner is displayed and contains required language.',
  },
  {
    id: 'nist-800-53-rev4-ac-11',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-11',
    title: 'Session Lock',
    description: 'The information system prevents further access to the system by initiating a session lock after a period of inactivity.',
    family: 'Access Control',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Configure automatic session lock after 15 minutes of inactivity.',
    assessmentGuidance: 'Test session lock functionality.',
  },
  {
    id: 'nist-800-53-rev4-ac-17',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AC-17',
    title: 'Remote Access',
    description: 'The organization authorizes, monitors, and controls all methods of remote access to the information system.',
    family: 'Access Control',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Require VPN, multi-factor authentication, and monitor remote access sessions.',
    assessmentGuidance: 'Review remote access logs and verify authentication requirements.',
  },
  
  // System and Information Integrity (SI) Family
  {
    id: 'nist-800-53-rev4-si-2',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SI-2',
    title: 'Flaw Remediation',
    description: 'The organization identifies, reports, and corrects information system flaws.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish vulnerability management process with patching timelines.',
    assessmentGuidance: 'Review patch management logs and verify critical patches are applied within SLA.',
  },
  {
    id: 'nist-800-53-rev4-si-3',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SI-3',
    title: 'Malicious Code Protection',
    description: 'The organization employs malicious code protection mechanisms at information system entry and exit points.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Deploy antivirus/anti-malware solutions and keep signatures updated.',
    assessmentGuidance: 'Verify antivirus is installed, updated, and scanning.',
  },
  {
    id: 'nist-800-53-rev4-si-4',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SI-4',
    title: 'Information System Monitoring',
    description: 'The organization monitors the information system to detect attacks and indicators of potential attacks.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement security information and event management (SIEM) system.',
    assessmentGuidance: 'Review monitoring logs and verify alerts are configured.',
  },
  {
    id: 'nist-800-53-rev4-si-7',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SI-7',
    title: 'Software, Firmware, and Information Integrity',
    description: 'The organization employs integrity verification tools to detect unauthorized changes to software, firmware, and information.',
    family: 'System and Information Integrity',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement file integrity monitoring (FIM) and code signing.',
    assessmentGuidance: 'Review integrity check logs and verify unauthorized changes are detected.',
  },
  
  // Audit and Accountability (AU) Family
  {
    id: 'nist-800-53-rev4-au-2',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AU-2',
    title: 'Audit Events',
    description: 'The organization determines that the information system is capable of auditing the following events.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Enable audit logging for authentication, authorization, and data access events.',
    assessmentGuidance: 'Verify audit logs capture required events.',
  },
  {
    id: 'nist-800-53-rev4-au-3',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AU-3',
    title: 'Content of Audit Records',
    description: 'The information system generates audit records containing information that establishes what type of event occurred, when, where, and the outcome.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Ensure audit logs include timestamp, user, action, resource, and result.',
    assessmentGuidance: 'Review sample audit logs and verify required fields are present.',
  },
  {
    id: 'nist-800-53-rev4-au-4',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AU-4',
    title: 'Audit Storage Capacity',
    description: 'The organization allocates audit record storage capacity and configures auditing to reduce the likelihood of such capacity being exceeded.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Configure log rotation and retention policies.',
    assessmentGuidance: 'Verify log storage capacity and rotation policies.',
  },
  {
    id: 'nist-800-53-rev4-au-5',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AU-5',
    title: 'Response to Audit Processing Failures',
    description: 'The information system alerts designated organizational officials in the event of an audit processing failure.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Configure alerts for audit log failures and storage capacity issues.',
    assessmentGuidance: 'Test audit failure scenarios and verify alerts are sent.',
  },
  {
    id: 'nist-800-53-rev4-au-6',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AU-6',
    title: 'Audit Review, Analysis, and Reporting',
    description: 'The organization reviews and analyzes information system audit records for indications of inappropriate or unusual activity.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish regular audit review schedule and automated analysis.',
    assessmentGuidance: 'Review audit analysis reports and verify reviews are conducted regularly.',
  },
  {
    id: 'nist-800-53-rev4-au-7',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AU-7',
    title: 'Audit Reduction and Report Generation',
    description: 'The information system provides an audit reduction and report generation capability.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement SIEM or log analysis tools for report generation.',
    assessmentGuidance: 'Verify audit reports can be generated and reviewed.',
  },
  {
    id: 'nist-800-53-rev4-au-8',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AU-8',
    title: 'Time Stamps',
    description: 'The information system uses internal system clocks to generate time stamps for audit records.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Synchronize system clocks using NTP.',
    assessmentGuidance: 'Verify time synchronization is configured and working.',
  },
  {
    id: 'nist-800-53-rev4-au-9',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'AU-9',
    title: 'Protection of Audit Information',
    description: 'The information system protects audit information and audit tools from unauthorized access, modification, and deletion.',
    family: 'Audit and Accountability',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Restrict access to audit logs and implement log integrity protection.',
    assessmentGuidance: 'Verify audit log access controls and integrity mechanisms.',
  },
  
  // Identification and Authentication (IA) Family
  {
    id: 'nist-800-53-rev4-ia-2',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'IA-2',
    title: 'Identification and Authentication (Organizational Users)',
    description: 'The information system uniquely identifies and authenticates organizational users.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement unique user IDs and strong authentication mechanisms.',
    assessmentGuidance: 'Verify user identification and authentication processes.',
  },
  {
    id: 'nist-800-53-rev4-ia-3',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'IA-3',
    title: 'Device Identification and Authentication',
    description: 'The information system uniquely identifies and authenticates devices before establishing a connection.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement device certificates or MAC address filtering.',
    assessmentGuidance: 'Verify device authentication is enforced.',
  },
  {
    id: 'nist-800-53-rev4-ia-4',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'IA-4',
    title: 'Identifier Management',
    description: 'The organization manages information system identifiers by receiving authorization from a designated organizational official.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Establish identifier assignment and management procedures.',
    assessmentGuidance: 'Review identifier management processes and verify authorization.',
  },
  {
    id: 'nist-800-53-rev4-ia-5',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'IA-5',
    title: 'Authenticator Management',
    description: 'The organization manages information system authenticators by establishing initial authenticator content, receiving authorization, and distributing authenticators.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement password policies, MFA, and secure authenticator distribution.',
    assessmentGuidance: 'Review authenticator management processes and verify compliance with policies.',
  },
  {
    id: 'nist-800-53-rev4-ia-6',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'IA-6',
    title: 'Authenticator Feedback',
    description: 'The information system obscures feedback of authentication information during the authentication process.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.LOW,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Mask passwords and sensitive input during authentication.',
    assessmentGuidance: 'Verify password masking and secure input handling.',
  },
  {
    id: 'nist-800-53-rev4-ia-7',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'IA-7',
    title: 'Cryptographic Module Authentication',
    description: 'The information system implements mechanisms for authentication to a cryptographic module.',
    family: 'Identification and Authentication',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Use FIPS 140-2 validated cryptographic modules.',
    assessmentGuidance: 'Verify cryptographic modules are FIPS 140-2 validated.',
  },
  
  // Configuration Management (CM) Family
  {
    id: 'nist-800-53-rev4-cm-2',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CM-2',
    title: 'Baseline Configuration',
    description: 'The organization develops, documents, and maintains baseline configurations for information systems.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Document and version control system configurations.',
    assessmentGuidance: 'Review baseline configuration documentation and verify it is maintained.',
  },
  {
    id: 'nist-800-53-rev4-cm-3',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CM-3',
    title: 'Configuration Change Control',
    description: 'The organization determines the types of changes to the information system that are configuration-controlled.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish change management process with approval workflows.',
    assessmentGuidance: 'Review change logs and verify approval processes are followed.',
  },
  {
    id: 'nist-800-53-rev4-cm-4',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CM-4',
    title: 'Security Impact Analysis',
    description: 'The organization analyzes changes to the information system to determine potential security impacts.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Perform security impact analysis for all configuration changes.',
    assessmentGuidance: 'Review security impact analyses and verify they are conducted.',
  },
  {
    id: 'nist-800-53-rev4-cm-5',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CM-5',
    title: 'Access Restrictions for Change',
    description: 'The organization defines, documents, approves, and enforces physical and logical access restrictions associated with changes to the information system.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Restrict configuration change access to authorized personnel.',
    assessmentGuidance: 'Review access controls and verify only authorized users can make changes.',
  },
  {
    id: 'nist-800-53-rev4-cm-6',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CM-6',
    title: 'Configuration Settings',
    description: 'The organization establishes and documents configuration settings for information technology products employed within the information system.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Use security configuration guides (e.g., DISA STIGs, CIS Benchmarks).',
    assessmentGuidance: 'Verify systems are configured according to security baselines.',
  },
  {
    id: 'nist-800-53-rev4-cm-7',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CM-7',
    title: 'Least Functionality',
    description: 'The organization configures the information system to provide only essential capabilities and prohibits or restricts the use of prohibited functions, ports, protocols, and/or services.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Disable unnecessary services and ports.',
    assessmentGuidance: 'Review system configurations and verify unnecessary services are disabled.',
  },
  {
    id: 'nist-800-53-rev4-cm-8',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CM-8',
    title: 'Information System Component Inventory',
    description: 'The organization develops and documents an inventory of information system components.',
    family: 'Configuration Management',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Maintain asset inventory with automated discovery where possible.',
    assessmentGuidance: 'Review inventory and verify it is accurate and up-to-date.',
  },
  
  // Contingency Planning (CP) Family
  {
    id: 'nist-800-53-rev4-cp-2',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CP-2',
    title: 'Contingency Plan',
    description: 'The organization develops and documents a contingency plan for the information system.',
    family: 'Contingency Planning',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Document recovery procedures and test regularly.',
    assessmentGuidance: 'Review contingency plan and verify it is tested.',
  },
  {
    id: 'nist-800-53-rev4-cp-3',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CP-3',
    title: 'Contingency Training',
    description: 'The organization provides contingency training to information system users.',
    family: 'Contingency Planning',
    priority: ControlSeverity.LOW,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct regular training on contingency procedures.',
    assessmentGuidance: 'Review training records and verify training is conducted.',
  },
  {
    id: 'nist-800-53-rev4-cp-4',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'CP-4',
    title: 'Contingency Plan Testing',
    description: 'The organization tests the contingency plan for the information system.',
    family: 'Contingency Planning',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct tabletop exercises and full recovery tests.',
    assessmentGuidance: 'Review test results and verify tests are conducted regularly.',
  },
  
  // Incident Response (IR) Family
  {
    id: 'nist-800-53-rev4-ir-4',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'IR-4',
    title: 'Incident Handling',
    description: 'The organization implements an incident handling capability for security incidents.',
    family: 'Incident Response',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish incident response team and procedures.',
    assessmentGuidance: 'Review incident logs and verify incidents are handled according to procedures.',
  },
  {
    id: 'nist-800-53-rev4-ir-5',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'IR-5',
    title: 'Incident Monitoring',
    description: 'The organization tracks and documents information system security incidents.',
    family: 'Incident Response',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Maintain incident tracking system and monitor for security events.',
    assessmentGuidance: 'Review incident tracking logs and verify monitoring is active.',
  },
  {
    id: 'nist-800-53-rev4-ir-6',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'IR-6',
    title: 'Incident Reporting',
    description: 'The organization requires personnel to report suspected security incidents.',
    family: 'Incident Response',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Establish reporting procedures and communication channels.',
    assessmentGuidance: 'Verify reporting procedures are documented and communicated.',
  },
  
  // Risk Assessment (RA) Family
  {
    id: 'nist-800-53-rev4-ra-2',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'RA-2',
    title: 'Security Categorization',
    description: 'The organization categorizes the information system and the information it processes, stores, and transmits.',
    family: 'Risk Assessment',
    priority: ControlSeverity.MODERATE,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Categorize systems according to FIPS 199.',
    assessmentGuidance: 'Review security categorization documentation.',
  },
  {
    id: 'nist-800-53-rev4-ra-3',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'RA-3',
    title: 'Risk Assessment',
    description: 'The organization conducts risk assessments to identify threats, vulnerabilities, and risks.',
    family: 'Risk Assessment',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct regular risk assessments and document findings.',
    assessmentGuidance: 'Review risk assessment reports and verify they are current.',
  },
  {
    id: 'nist-800-53-rev4-ra-5',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'RA-5',
    title: 'Vulnerability Scanning',
    description: 'The organization scans for vulnerabilities in the information system and applications.',
    family: 'Risk Assessment',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Conduct regular vulnerability scans and remediate findings.',
    assessmentGuidance: 'Review scan results and verify vulnerabilities are tracked and remediated.',
  },
  
  // System and Communications Protection (SC) Family
  {
    id: 'nist-800-53-rev4-sc-5',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SC-5',
    title: 'Denial of Service Protection',
    description: 'The information system protects against or limits the effects of denial-of-service attacks.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement rate limiting, DDoS protection, and resource quotas.',
    assessmentGuidance: 'Review DoS protection configurations and test resilience.',
  },
  {
    id: 'nist-800-53-rev4-sc-7',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SC-7',
    title: 'Boundary Protection',
    description: 'The information system monitors and controls communications at the external boundary and key internal boundaries.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.HIGH,
    baseline: ['LOW', 'MODERATE', 'HIGH'],
    implementationGuidance: 'Implement firewalls, network segmentation, and traffic filtering.',
    assessmentGuidance: 'Review firewall rules and network segmentation.',
  },
  {
    id: 'nist-800-53-rev4-sc-8',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SC-8',
    title: 'Transmission Confidentiality and Integrity',
    description: 'The information system protects the confidentiality and integrity of transmitted information.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Use TLS/SSL for data in transit and verify certificates.',
    assessmentGuidance: 'Review TLS configurations and verify encryption is enforced.',
  },
  {
    id: 'nist-800-53-rev4-sc-12',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SC-12',
    title: 'Cryptographic Key Establishment and Management',
    description: 'The organization establishes and manages cryptographic keys for required cryptography.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Implement key management system with key rotation policies.',
    assessmentGuidance: 'Review key management procedures and verify keys are rotated.',
  },
  {
    id: 'nist-800-53-rev4-sc-13',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SC-13',
    title: 'Cryptographic Protection',
    description: 'The information system implements cryptographic mechanisms.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.MODERATE,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Use approved cryptographic algorithms and key lengths.',
    assessmentGuidance: 'Verify cryptographic implementations meet requirements.',
  },
  {
    id: 'nist-800-53-rev4-sc-28',
    framework: ComplianceFramework.NIST_800_53_REV_4,
    controlId: 'SC-28',
    title: 'Protection of Information at Rest',
    description: 'The information system protects the confidentiality and integrity of information at rest.',
    family: 'System and Communications Protection',
    priority: ControlSeverity.HIGH,
    baseline: ['MODERATE', 'HIGH'],
    implementationGuidance: 'Encrypt sensitive data at rest using approved algorithms.',
    assessmentGuidance: 'Verify encryption is enabled for data at rest.',
  },
];

