name: Compliance Testing

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  compliance-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run compliance tests
        run: |
          npm run test:compliance
        env:
          TEST_HARNESS_CONFIG: ${{ secrets.TEST_HARNESS_CONFIG }}
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: compliance-test-results
          path: heimdall-framework/reports/*

      - name: Check compliance status
        run: |
          node heimdall-framework/ci-cd/check-compliance.js
        continue-on-error: false

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Find the latest compliance report
            const reportsDir = 'heimdall-framework/reports';
            let reportPath = path.join(reportsDir, 'compliance-report.json');
            
            if (!fs.existsSync(reportPath)) {
              const files = fs.readdirSync(reportsDir).filter(f => 
                f.startsWith('compliance-report-') && f.endsWith('.json')
              );
              if (files.length > 0) {
                files.sort((a, b) => {
                  const timestampA = parseInt(a.match(/compliance-report-(\d+)\.json/)?.[1] || '0');
                  const timestampB = parseInt(b.match(/compliance-report-(\d+)\.json/)?.[1] || '0');
                  return timestampB - timestampA;
                });
                reportPath = path.join(reportsDir, files[0]);
              }
            }
            
            const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
            
            const comment = `## Compliance Test Results
            
            **Overall Score:** ${report.summary.passRate}%
            
            **Tests:** ${report.summary.passedTests}/${report.summary.totalTests} passed
            
            ${report.summary.failedTests > 0 ? `⚠️ **${report.summary.failedTests} tests failed**` : '✅ All tests passed'}
            
            ${report.summary.failedTests > 0 ? 'This PR cannot be merged until compliance issues are resolved.' : ''}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
